### PR TITLE
update url for atv, rob tv, tvl, tv oost

### PR DESCRIPTION
**Pull request by peno64**
Update the url from atv. The old one doesn't work  anymore

### CODE REVIEW

**Comment by Bart80-1** [comment]
Hi, I notice that this PR will probably make regio TV work again (whereas it's not the case for a lot of users now), is there something I (as dev with no knowledge to this codebase) can do to help?

**Comment by peno64** [comment]
@Bart80-1 Someone of the developers attached to this project just must approve this PR...

**Comment by peno64** [comment]
@dagwieers @michaelarnauts Zou één van jullie mijn PR eens kunnen approven zodat de regio tv terug werkt?

**Comment by Borromini** [comment]
Anyone got an update on the API/URL for ATV? They moved to the Gazet van Antwerpen website, it seems.

https://player.agnoplay.com/embed/gvaatv-live

**Comment by dagwieers** [comment]
@peno64 Sorry, I had not seen your comment. I am no longer using Kodi myself, so I made you admin of this project.

**Comment by peno64** [comment]
Thx

**Comment by peno64** [comment]
@Borromini The addon is updated. You can install the latest release.

**Comment by Borromini** [comment]
Thanks!

**Pull request merged**
